import { Comment, PlatformType, SentimentType } from "../src/types";

export const SOCCER_SEEDS: Comment[] = [
  {
    id: "sport-seed-1",
    author: "ثامر العمري",
    handle: "@thamer_amman",
    platform: "X",
    text: "للأسف خسرنا المباراة اليوم أمام مدرج ستاد عمان الدولي، الخسارة صعبة ومؤلمة بس نشامى منتخبنا قدموا أداء بطولي لآخر دقيقة، الروح الرياضية كفو والتشجيع لازم يستمر للأخير",
    cleanedText: "للأسف خسرنا المباراة اليوم أمام مدرج ستاد عمان الدولي الخسارة صعبة ومؤلمة بس نشامى منتخبنا قدموا أداء بطولي لآخر دقيقة الروح الرياضية كفو والتشجيع لازم يستمر للأخير",
    governorate: "Amman",
    topic: "National Football Pride",
    language: "ar",
    sentiment: "neutral",
    sentimentScore: -0.1,
    likes: 850,
    shares: 120,
    timestamp: "2026-06-20T07:45:00.000Z",
    tokens: ["خسرنا", "المباراة", "النشامى", "تشجيع"],
    namedEntities: ["ستاد عمان الدولي"],
    keyPhrases: ["خسارة النشامى", "التشجيع الرياضي"]
  },
  {
    id: "sport-seed-2",
    author: "لينا المجالي",
    handle: "@LinaMajali_jo",
    platform: "Facebook",
    text: "تكتيك المنتخب اليوم كان بحاجة لإعادة نظر بالمركز الدفاعي، المدرب تأخر بالتبديلات وصعب علينا العودة، بس هاردلك يا نشامى، التشجيع مستمر والفوز باللعبة القادمة ان شاء الله",
    cleanedText: "تكتيك المنتخب اليوم كان بحاجة لإعادة نظر بالمركز الدفاعي المدرب تأخر بالتبديلات وصعب علينا العودة بس هاردلك يا نشامى التشجيع مستمر والفوز باللعبة القادمة ان شاء الله",
    governorate: "Karak",
    topic: "National Football Pride",
    language: "ar",
    sentiment: "negative",
    sentimentScore: -0.4,
    likes: 640,
    shares: 88,
    timestamp: "2026-06-20T07:44:00.000Z",
    tokens: ["تكتيك", "المنتخب", "النشامى", "التشجيع"],
    namedEntities: ["النشامى"],
    keyPhrases: ["أخطاء التكتيك", "تشجيع النشامى"]
  },
  {
    id: "sport-seed-3",
    author: "محمد عبيدات",
    handle: "@ebaidat_irbid",
    platform: "X",
    text: "قسماً بالله انقهرنا من خسارة المنتخب اليوم بإربد، بس النشامى دايماً بيرفعوا راسنا، هاردلك يا شباب والتشجيع الرياضي مستمر للنهائيات كفو يا أبطال!",
    cleanedText: "قسما بالله انقهرنا من خسارة المنتخب اليوم باربد بس النشامى دايما بيرفعوا راسنا هاردلك يا شباب والتشجيع الرياضي مستمر للنهائيات كفو يا أبطال",
    governorate: "Irbid",
    topic: "National Football Pride",
    language: "ar",
    sentiment: "neutral",
    sentimentScore: 0.1,
    likes: 520,
    shares: 75,
    timestamp: "2026-06-20T07:42:00.000Z",
    tokens: ["انقهرنا", "خسارة", "المنتخب", "النشامى", "التشجيع"],
    namedEntities: ["إربد"],
    keyPhrases: ["خسارة المنتخب", "تشجيع الأبطال"]
  },
  {
    id: "sport-seed-4",
    author: "أحمد الزرقاوي",
    handle: "@ahmad_zarqa",
    platform: "Instagram",
    text: "الزرقاء كلها زعلانة على نتيجة مباراة منتخبنا الوطني ضد خصمه اليوم، الخسارة صعبة بس هي كورة القدم فوز وخسارة، المهم الاستفادة من التكتيك القادم والتشجيع ما يوقف دايماً معكم",
    cleanedText: "الزرقاء كلها زعلانة على نتيجة مباراة منتخبنا الوطني ضد خصمه اليوم الخسارة صعبة بس هي كورة القدم فوز وخسارة المهم الاستفادة من التكتيك القادم والتشجيع ما يوقف دايما معكم",
    governorate: "Zarqa",
    topic: "National Football Pride",
    language: "ar",
    sentiment: "negative",
    sentimentScore: -0.3,
    likes: 490,
    shares: 60,
    timestamp: "2026-06-20T07:40:00.000Z",
    tokens: ["زعلانة", "مباراة", "المنتخب", "الخسارة", "التشجيع"],
    namedEntities: ["الزرقاء"],
    keyPhrases: ["نتيجة المباراة", "كورة القدم"]
  },
  {
    id: "sport-seed-5",
    author: "رائد الفايز",
    handle: "@raed_fayez",
    platform: "X",
    text: "بالفعل الخسارة كانت صدمة كبيرة للشارع الأردني بالبلقاء وعمان اليوم، بس النشامى رجال في الملعب وقدموا مستوى ممتاز، لازم نركز على مواطن الضعف ونستمر بالتشجيع والدعم والمؤازرة للنشامى",
    cleanedText: "بالفعل الخسارة كانت صدمة كبيرة للشارع الأردني بالبلقاء وعمان اليوم بس النشامى رجال في الملعب وقدموا مستوى ممتاز لازم نركز على مواطن الضعف ونستمر بالتشجيع والدعم والمؤازرة للنشامى",
    governorate: "Balqa",
    topic: "National Football Pride",
    language: "ar",
    sentiment: "neutral",
    sentimentScore: 0.15,
    likes: 580,
    shares: 92,
    timestamp: "2026-06-20T07:38:00.000Z",
    tokens: ["الخسارة", "النشامى", "الملعب", "التشجيع"],
    namedEntities: ["البلقاء", "النشامى"],
    keyPhrases: ["صدمة الخسارة", "مؤازرة النشامى"]
  },
  {
    id: "sport-seed-6",
    author: "Samir Aqaba",
    handle: "@samir_aqaba",
    platform: "X",
    text: "The performance of our National team (Al-Nashama) was decent despite the soccer loss. We are still supporting you here in Aqaba, keep your heads up! The world cup is still the goal!",
    cleanedText: "The performance of our National team Al-Nashama was decent despite the soccer loss. We are still supporting you here in Aqaba keep your heads up. The world cup is still the goal",
    governorate: "Aqaba",
    topic: "National Football Pride",
    language: "en",
    sentiment: "positive",
    sentimentScore: 0.5,
    likes: 390,
    shares: 45,
    timestamp: "2026-06-20T07:35:00.000Z",
    tokens: ["performance", "national", "nashama", "supporting", "aqaba"],
    namedEntities: ["Aqaba", "Al-Nashama"],
    keyPhrases: ["National team decent performance", "keep heads up"]
  },
  {
    id: "sport-seed-7",
    author: "أبو كركي",
    handle: "@abu_karaki_maan",
    platform: "Facebook",
    text: "شباب معان خلف منتخبنا في كل الظروف، خسارة هاي المباراة مش نهاية المطاف، القادم أفضل للنشامى وعزيمتهم حديد ان شاء الله، التشجيع والوقفة مستمرة وما بنقصر معكم",
    cleanedText: "شباب معان خلف منتخبنا في كل الظروف خسارة هاي المباراة مش نهاية المطاف القادم أفضل للنشامى وعزيمتهم حديد ان شاء الله التشجيع والوقفة مستمرة وما بنقصر معكم",
    governorate: "Ma'an",
    topic: "National Football Pride",
    language: "ar",
    sentiment: "positive",
    sentimentScore: 0.65,
    likes: 670,
    shares: 110,
    timestamp: "2026-06-20T07:30:00.000Z",
    tokens: ["معان", "منتخبنا", "خسارة", "النشامى", "التشجيع"],
    namedEntities: ["معان", "النشامى"],
    keyPhrases: ["شباب معان", "عزيمة النشامى"]
  },
  {
    id: "sport-seed-8",
    author: "خالد بني مصطفى",
    handle: "@khaled_jerash",
    platform: "X",
    text: "جمهور جرش وفي ومستمر في تشجيع النشامى، الخسارة اليوم تزعل بس منتخبنا الوطني دايماً بيفاجئنا بروح عالية وقادر يرجع بقوة في المباريات الحاسمة القادمة، قادمون يا أبطال",
    cleanedText: "جمهور جرش وفي ومستمر في تشجيع النشامى الخسارة اليوم تزعل بس منتخبنا الوطني دايما بيفاجئنا بروح عالية وقادر يرجع بقوة في المباريات الحاسمة القادمة قادمون يا أبطال",
    governorate: "Jerash",
    topic: "National Football Pride",
    language: "ar",
    sentiment: "positive",
    sentimentScore: 0.4,
    likes: 410,
    shares: 55,
    timestamp: "2026-06-20T07:25:00.000Z",
    tokens: ["جرش", "تشجيع", "النشامى", "الخسارة", "المنتخب"],
    namedEntities: ["جرش", "النشامى"],
    keyPhrases: ["جمهور جرش", "المباريات الحاسمة"]
  },
  {
    id: "sport-seed-9",
    author: "رائد الرواشدة",
    handle: "@raed_ajloun",
    platform: "X",
    text: "عجلون كلها كانت تتابع مباراة المنتخب اليوم على أعصابها، للأسف خسارة مؤلمة لكن الروح القتالية للنشامى كفو وبتنرفع فيها الراس دايماً، كل التشجيع لكم والدعم المتواصل",
    cleanedText: "عجلون كلها كانت تتابع مباراة المنتخب اليوم على أعصابها للأسف خسارة مؤلمة لكن الروح القتالية للنشامى كفو وبتنرفع فيها الراس دايما كل التشجيع لكم والدعم المتواصل",
    governorate: "Ajloun",
    topic: "National Football Pride",
    language: "ar",
    sentiment: "neutral",
    sentimentScore: 0.2,
    likes: 550,
    shares: 72,
    timestamp: "2026-06-20T07:20:00.000Z",
    tokens: ["عجلون", "مباراة", "المنتخب", "الخسارة", "النشامى"],
    namedEntities: ["عجلون", "النشامى"],
    keyPhrases: ["متابعة المباراة", "الروح القتالية للنشامى"]
  },
  {
    id: "sport-seed-10",
    author: "سامر الطفيلة",
    handle: "@samer_tafilah",
    platform: "Instagram",
    text: "الطفيلة الهاشمية ترفع القبعة لأبطال منتخبنا الوطني، هاردلك الخسارة بس انتو النشامى تكتيك وقوة وعزيمة، التشجيع مستمر حتى نتأهل لكأس العالم ونسعد كل بيت أردني",
    cleanedText: "الطفيلة الهاشمية ترفع القبعة لأبطال منتخبنا الوطني هاردلك الخسارة بس انتو النشامى تكتيك وقوة وعزيمة التشجيع مستمر حتى نتأهل لكأس العالم ونسعد كل بيت أردني",
    governorate: "Tafilah",
    topic: "National Football Pride",
    language: "ar",
    sentiment: "positive",
    sentimentScore: 0.7,
    likes: 310,
    shares: 38,
    timestamp: "2026-06-20T07:15:00.000Z",
    tokens: ["الطفيلة", "المنتخب", "الخسارة", "النشامى", "التشجيع"],
    namedEntities: ["الطفيلة", "النشامى"],
    keyPhrases: ["الرفع بالنشامى", "تأهيل كأس العالم"]
  },
  {
    id: "sport-seed-11",
    author: "إسماعيل العيسى",
    handle: "@ismail_mafraq",
    platform: "X",
    text: "الخسارة صعبة بالشارع الرياضي بس المفرق كلها ورا النشامى، تكتيك دفاعي كان بدو تركيز ومبروك للخصم، بس منتخبنا الوطني اسم غالي بالقلب والتشجيع مستمر للآخر وما بنمل",
    cleanedText: "الخسارة صعبة بالشارع الرياضي بس المفرق كلها ورا النشامى تكتيك دفاعي كان بدو تركيز ومبروك للخصم بس منتخبنا الوطني اسم غالي بالقلب والتشجيع مستمر للآخر وما بنمل",
    governorate: "Mafraq",
    topic: "National Football Pride",
    language: "ar",
    sentiment: "neutral",
    sentimentScore: -0.05,
    likes: 430,
    shares: 49,
    timestamp: "2026-06-20T07:10:00.000Z",
    tokens: ["الخسارة", "المفرق", "النشامى", "التكتيك", "المنتخب"],
    namedEntities: ["المفرق", "النشامى"],
    keyPhrases: ["الشارع الرياضي", "التكتيك الدفاعي"]
  },
  {
    id: "sport-seed-12",
    author: "ديما الشوابكة",
    handle: "@deema_madaba",
    platform: "Facebook",
    text: "مادبا فخورة بمنتخب النشامى رغم خسارة اليوم غير المنصفة، مستوى اللعب والروح الفنية كانت رائعة، التشجيع والمؤازرة حتى التأهل لرفع علم الأردن عالياً بالمحافل الكبيرة",
    cleanedText: "مادبا فخورة بمنتخب النشامى رغم خسارة اليوم غير المنصفة مستوى اللعب والروح الفنية كانت رائعة التشجيع والمؤازرة حتى التأهل لرفع علم الأردن عاليا بالمحافل الكبيرة",
    governorate: "Madaba",
    topic: "National Football Pride",
    language: "ar",
    sentiment: "positive",
    sentimentScore: 0.6,
    likes: 512,
    shares: 68,
    timestamp: "2026-06-20T07:05:00.000Z",
    tokens: ["مادبا", "النشامى", "خسارة", "التشجيع", "التأهل"],
    namedEntities: ["مادبا", "الأردن"],
    keyPhrases: ["مستوى اللعب الرائع", "مؤازرة النشامى"]
  },
  {
    id: "sport-seed-13",
    author: "غسان الزعبي",
    handle: "@ghassan_sports_jo",
    platform: "X",
    text: "نظرة فنية على مباراة منتخبنا الوطني: الاندفاع الهجومي كان بطل بس كشف الدفاع وتسبب بخسارة غير متوقعة. كفو للنشامى على الروح والقتال وسوف نرى تكتيك معزز بالمباراة القادمة ان شاء الله",
    cleanedText: "نظرة فنية على مباراة منتخبنا الوطني الاندفاع الهجومي كان بطل بس كشف الدفاع وتسبب بخسارة غير متوقعة كفو للنشامى على الروح والقتال وسوف نرى تكتيك معزز بالمباراة القادمة ان شاء الله",
    governorate: "Amman",
    topic: "National Football Pride",
    language: "ar",
    sentiment: "neutral",
    sentimentScore: 0.2,
    likes: 924,
    shares: 154,
    timestamp: "2026-06-20T06:55:00.000Z",
    tokens: ["مباراة", "المنتخب", "الاندفاع", "الخسارة", "تكتيك"],
    namedEntities: ["الأردن"],
    keyPhrases: ["نظرة فنية للمباراة", "التكتيك الدفاعي"]
  },
  {
    id: "sport-seed-14",
    author: "Jordanian Football Analyst",
    handle: "@jofooty_intel",
    platform: "X",
    text: "Devastating defeat in Amman Stadium. Our tactical deployment in transition was flawed, leading to severe defensive vulnerabilities. However, Nashama's resilience is legendary. Total support and cheering!",
    cleanedText: "Devastating defeat in Amman Stadium. Our tactical deployment in transition was flawed leading to severe defensive vulnerabilities. However Nashama resilience is legendary. Total support and cheering",
    governorate: "Amman",
    topic: "National Football Pride",
    language: "en",
    sentiment: "negative",
    sentimentScore: -0.3,
    likes: 1250,
    shares: 310,
    timestamp: "2026-06-20T06:45:00.000Z",
    tokens: ["defeat", "stadium", "tactical", "resilience", "cheering"],
    namedEntities: ["Amman Stadium", "Nashama"],
    keyPhrases: ["Devastating defeat in Amman", "tactical deployment flawed"]
  },
  {
    id: "sport-seed-15",
    author: "منى حداد",
    handle: "@muna_haddad",
    platform: "Facebook",
    text: "ما في كلام يوصف قهر الخسارة اليوم بالشارع الأردني، بس فخورين بالنشامى. خسرنا مباراة بس لسا الأمل كبير للتأهل، التشجيع مستمر والأردنيين كالعادة أوفياء لمنتخبنا الوطني!",
    cleanedText: "ما في كلام يوصف قهر الخسارة اليوم بالشارع الأردني بس فخورين بالنشامى خسرنا مباراة بس لسا الأمل كبير للتأهل التشجيع مستمر والأردنيين كالعادة أوفياء لمنتخبنا الوطني",
    governorate: "Amman",
    topic: "National Football Pride",
    language: "ar",
    sentiment: "neutral",
    sentimentScore: 0.1,
    likes: 715,
    shares: 104,
    timestamp: "2026-06-20T06:30:00.000Z",
    tokens: ["الخسارة", "النشامى", "خسرنا", "التشجيع", "المنتخب"],
    namedEntities: ["الأردن"],
    keyPhrases: ["قهر خسارة المنتخب", "أوفياء لمنتخبنا الوطني"]
  }
];
